#!/usr/bin/env python3
"""
deadline-monitor.py — Runs on SessionStart.
Scans workspace tasks and leads, writes today's daily brief.
Ported from .opencode/plugins/deadline-monitor.ts
"""
import os
import sys
from datetime import date, datetime, timezone
from pathlib import Path

WORKSPACE = os.environ.get("CLAUDE_PLUGIN_OPTION_WORKSPACE_ROOT", os.getcwd())


def parse_frontmatter(content: str) -> dict:
    """Parse YAML frontmatter from markdown. Returns empty dict if none found."""
    if not content.startswith("---"):
        return {}
    end = content.find("---", 3)
    if end == -1:
        return {}
    result = {}
    for line in content[3:end].splitlines():
        if ":" in line:
            key, _, val = line.partition(":")
            result[key.strip()] = val.strip().strip("\"'")
    return result


def days_until(date_str: str):
    """Days from today to date_str. Negative = overdue. None if unparseable."""
    try:
        return (date.fromisoformat(date_str) - date.today()).days
    except (ValueError, TypeError):
        return None


def priority_icon(priority: str) -> str:
    return {"urgent": "🔴", "high": "🟠", "medium": "🟡", "low": "⚪"}.get(priority.lower(), "⚪")


def task_line(fm: dict, filename: str) -> str:
    title = fm.get("title", Path(filename).stem)
    project = fm.get("project", "—")
    priority = fm.get("priority", "medium")
    due = fm.get("due", "")
    due_str = f" — Due: {due}" if due else ""
    return f"- {priority_icon(priority)} **{title}** — {project}{due_str}"


def scan_tasks(tasks_dir: Path) -> dict:
    buckets = {"overdue": [], "today": [], "week": [], "in_progress": [], "blocked": []}
    if not tasks_dir.exists():
        return buckets
    for f in tasks_dir.glob("*.md"):
        try:
            fm = parse_frontmatter(f.read_text(encoding="utf-8"))
            line = task_line(fm, f.name)
            status = fm.get("status", "")
            if status == "blocked":
                buckets["blocked"].append(line)
            elif status == "in-progress":
                buckets["in_progress"].append(line)
            due = fm.get("due", "")
            if due:
                days = days_until(due)
                if days is not None:
                    if days < 0:
                        buckets["overdue"].append(line)
                    elif days == 0:
                        buckets["today"].append(line)
                    elif days <= 7:
                        buckets["week"].append(line)
        except Exception:
            pass
    return buckets


def scan_leads(leads_dir: Path):
    counts = {s: 0 for s in ("new", "contacted", "qualified", "nurturing", "closed")}
    stale = []
    if not leads_dir.exists():
        return counts, stale
    for f in leads_dir.glob("*.md"):
        try:
            fm = parse_frontmatter(f.read_text(encoding="utf-8"))
            status = fm.get("status", "new").lower()
            if status in counts:
                counts[status] += 1
            if status in ("contacted", "qualified", "nurturing"):
                updated = fm.get("updated", "")
                if updated:
                    days = days_until(updated)
                    if days is not None and days <= -7:
                        company = fm.get("company") or fm.get("title") or f.stem
                        stale.append(company)
        except Exception:
            pass
    return counts, stale


def write_brief(tasks: dict, lead_counts: dict, stale_leads: list):
    today = date.today()
    date_str = today.isoformat()
    # Cross-platform date formatting
    try:
        display = today.strftime("%-d %B %Y") if sys.platform != "win32" else today.strftime("%d %B %Y").lstrip("0")
    except ValueError:
        display = today.strftime("%d %B %Y")
    day_name = today.strftime("%A")
    now_utc = datetime.now(timezone.utc).strftime("%H:%M:%S")

    brief_dir = Path(WORKSPACE) / "notes" / "daily"
    brief_dir.mkdir(parents=True, exist_ok=True)

    lines = [
        "---",
        f"title: Daily Brief — {day_name}, {display}",
        "type: daily-brief",
        f"date: {date_str}",
        f"created: {date_str}",
        f"updated: {date_str}",
        "status: active",
        "---",
        "",
        f"# 📋 Daily Brief — {day_name}, {display}",
        "",
        "> Auto-generated by lead-agent plugin on session start. Say \"brief me\" for the full briefing.",
        "",
    ]

    has_alerts = tasks["overdue"] or tasks["blocked"] or stale_leads
    if has_alerts:
        lines.append("## ⚠️ Needs Attention")
        if tasks["overdue"]:
            lines.append(f"### Overdue Tasks ({len(tasks['overdue'])})")
            lines.extend(tasks["overdue"])
            lines.append("")
        if tasks["blocked"]:
            lines.append(f"### Blocked Tasks ({len(tasks['blocked'])})")
            lines.extend(tasks["blocked"])
            lines.append("")
        if stale_leads:
            lines.append("### Leads Going Cold (no touch in 7+ days)")
            lines.extend(f"- 🧊 {l}" for l in stale_leads)
            lines.append("")

    lines.append("## 📋 Today's Tasks")
    lines.extend(tasks["today"] if tasks["today"] else ["- No tasks due today."])
    lines.append("")

    if tasks["in_progress"]:
        lines.append("## 🔄 In Progress")
        lines.extend(tasks["in_progress"])
        lines.append("")

    if tasks["week"]:
        lines.append("## 📅 Due This Week")
        lines.extend(tasks["week"])
        lines.append("")

    lines += [
        "## 🔄 Lead Pipeline",
        "| Stage | Count |",
        "|-------|-------|",
    ]
    for stage in ("new", "contacted", "qualified", "nurturing", "closed"):
        lines.append(f"| {stage.capitalize()} | {lead_counts.get(stage, 0)} |")
    lines.append("")

    if stale_leads:
        lines.append(f"**Follow-up needed**: {', '.join(stale_leads)}")
        lines.append("")

    lines += ["---", f"*Brief auto-generated at {now_utc} UTC*"]

    brief_file = brief_dir / f"{date_str}-brief.md"
    brief_file.write_text("\n".join(lines), encoding="utf-8")


def main():
    workspace = Path(WORKSPACE)
    tasks = scan_tasks(workspace / "documents" / "tasks" / "active")
    lead_counts, stale_leads = scan_leads(workspace / "documents" / "leads")
    write_brief(tasks, lead_counts, stale_leads)


if __name__ == "__main__":
    try:
        main()
    except Exception:
        # Never interrupt session on plugin failure
        sys.exit(0)
