#!/usr/bin/env python3
"""
deadline-monitor.py — Runs on SessionStart.
Scans workspace leads and writes today's daily brief.
"""
import os
import sys
from datetime import date, datetime, timezone
from pathlib import Path

WORKSPACE = os.environ.get("CLAUDE_PLUGIN_OPTION_WORKSPACE_ROOT", os.getcwd())


def parse_frontmatter(content: str) -> dict:
    """Parse YAML frontmatter from markdown. Returns empty dict if none found."""
    if not content.startswith("---"):
        return {}
    end = content.find("---", 3)
    if end == -1:
        return {}
    result = {}
    for line in content[3:end].splitlines():
        if ":" in line:
            key, _, val = line.partition(":")
            result[key.strip()] = val.strip().strip("\"'")
    return result


def days_until(date_str: str):
    """Days from today to date_str. Negative = overdue. None if unparseable."""
    try:
        return (date.fromisoformat(date_str) - date.today()).days
    except (ValueError, TypeError):
        return None


def scan_leads(leads_dir: Path):
    counts = {s: 0 for s in ("new", "prospect", "contacted", "qualified", "nurturing", "closed")}
    stale = []
    if not leads_dir.exists():
        return counts, stale
    for f in leads_dir.glob("*.md"):
        try:
            fm = parse_frontmatter(f.read_text(encoding="utf-8"))
            status = fm.get("status", "new").lower()
            if status in counts:
                counts[status] += 1
            if status in ("contacted", "qualified", "nurturing"):
                updated = fm.get("updated", "")
                if updated:
                    days = days_until(updated)
                    if days is not None and days <= -7:
                        company = fm.get("company") or fm.get("title") or f.stem
                        stale.append(company)
        except Exception:
            pass
    return counts, stale


def write_brief(lead_counts: dict, stale_leads: list):
    today = date.today()
    date_str = today.isoformat()
    try:
        display = today.strftime("%-d %B %Y") if sys.platform != "win32" else today.strftime("%d %B %Y").lstrip("0")
    except ValueError:
        display = today.strftime("%d %B %Y")
    day_name = today.strftime("%A")
    now_utc = datetime.now(timezone.utc).strftime("%H:%M:%S")

    brief_dir = Path(WORKSPACE) / "notes" / "daily"
    brief_dir.mkdir(parents=True, exist_ok=True)

    lines = [
        "---",
        f"title: Daily Brief — {day_name}, {display}",
        "type: daily-brief",
        f"date: {date_str}",
        f"created: {date_str}",
        f"updated: {date_str}",
        "status: active",
        "---",
        "",
        f"# 📋 Daily Brief — {day_name}, {display}",
        "",
        "> Auto-generated by prospect-studio on session start. Say \"brief me\" for the full briefing.",
        "",
    ]

    if stale_leads:
        lines.append("## ⚠️ Needs Attention")
        lines.append("### Leads Going Cold (no touch in 7+ days)")
        lines.extend(f"- 🧊 {l}" for l in stale_leads)
        lines.append("")

    lines += [
        "## 🔄 Lead Pipeline",
        "| Stage | Count |",
        "|-------|-------|",
    ]
    for stage in ("new", "prospect", "contacted", "qualified", "nurturing", "closed"):
        lines.append(f"| {stage.capitalize()} | {lead_counts.get(stage, 0)} |")
    lines.append("")

    if stale_leads:
        lines.append(f"**Follow-up needed**: {', '.join(stale_leads)}")
        lines.append("")

    lines += ["---", f"*Brief auto-generated at {now_utc} UTC*"]

    brief_file = brief_dir / f"{date_str}-brief.md"
    brief_file.write_text("\n".join(lines), encoding="utf-8")


def main():
    workspace = Path(WORKSPACE)
    lead_counts, stale_leads = scan_leads(workspace / "documents" / "leads")
    write_brief(lead_counts, stale_leads)


if __name__ == "__main__":
    try:
        main()
    except Exception:
        sys.exit(0)
